# name: Create Release Branch

# on:
#   push:
#     tags:
#       - '*'
#     # branches:
#     #   - main
  
#   workflow_dispatch:

# jobs:
#   create-release-branch:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Check if it's a tag push
#       run: echo "This is a tag push."

#     - name: Check out code
#       uses: actions/checkout@v2  # This checks out your repository, including Git

#     - name: Cache Git
#       uses: actions/cache@v2
#       with:
#         path: ~/.git-standalone  # The path where Git will be cached
#         key: git-${{ runner.os }}-${{ hashFiles('**/.gitconfig') }}  # Cache key based on OS and .gitconfig

#     - name: Install Git
#       if: steps.cache.outputs.cache-hit != 'true'  # Only install Git if cache is not hit
#       run: |
#         sudo apt-get update
#         sudo apt-get install git -y

#     - name: Display Git version
#       run: git --version


#       # create release branch 

#     - name: Create Release Branch
#       run: |
#         # Extract the tag name from the ref
#         TAG_NAME=${GITHUB_REF#refs/tags/}
#         echo $TAG_NAME
        
#         git checkout origin main
#         git pull origin main


#         # Create a release branch
#         git checkout -b release/${TAG_NAME}

#         # Push the new branch to the remote repository
#         git push origin release/${TAG_NAME}

#       env:
#         GITHUB_TOKEN: ${{ secrets.TOKEN }}
