name: Create Branch from Tag

on:
  push:
    tags:
      - '*'

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Extract tag name
        id: extract-tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create branch
        run: git checkout -b release/$TAG_NAME $TAG_NAME

      - name: Push branch to remote
        run: git push origin release/$TAG_NAME
