name: Update Release Branch

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - master
      - 'release/**'  # Assuming release branches follow a pattern like 'release/{version}'

jobs:
  update-release-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Extract Tag Name
      id: tag
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

    - name: Extract Tag Author Identity
      id: author
      run: echo "::set-output name=author::$(git show -s --format='%an <%ae>' ${{ steps.tag.outputs.tag }}^{})"

    - name: Create Release Branch
      run: |
        TAG_NAME="${{ steps.tag.outputs.tag }}"
        BRANCH_NAME="release/$TAG_NAME"
        git checkout -b $BRANCH_NAME
        git push origin $BRANCH_NAME

    - name: Update package.json Version
      run: |
        TAG_NAME="${{ steps.tag.outputs.tag }}"
        sed -i "s/\"version\": \".*\"/\"version\": \"$TAG_NAME\"/" package.json
        git add package.json
        git commit -m "Update package.json version to $TAG_NAME"
        # git push

    - name: Update package-lock.json Version
      run: |
        TAG_NAME="${{ steps.tag.outputs.tag }}"
        sed -i "s/\"version\": \".*\"/\"version\": \"$TAG_NAME\"/" package-lock.json
        git add package-lock.json
        git commit -m "Update package-lock.json version to $TAG_NAME"
        # git push

    - name: Update config.xml Version
      run: |
        TAG_NAME="${{ steps.tag.outputs.tag }}"
        sed -i "s/version=\"[^\"]*\"/version=\"$TAG_NAME\"/" config.xml
        git add config.xml
        git commit -m "Update config.xml version to $TAG_NAME"
        # git push

    - name: Set Commit Author Identity
      run: git config user.name "${{ steps.author.outputs.author }}" && git config user.email ""

    - name: Push Changes with Author Identity
      run: git push
